### PR TITLE
Fix compilation errors with recent PRs

### LINKED ISSUE #88: New Record superclass breaks testers.
ucb-bar/chisel3@2e6444cc55b54b59f781a14823e219d9a2413f72 causes:

    [error] .../ucb-bar/chisel-testers/src/main/scala/chisel3/iotesters/OrderedDecoupledHWIOTester.scala:394: type mismatch;
    [error]  found   : chisel3.core.Record
    [error]  required: chisel3.Bundle
    [error]     (which expands to)  chisel3.core.Bundle
    [error]     io_info = new IOAccessor(device_under_test.io)
    [error]                                                ^
    [error] .../ucb-bar/chisel-testers/src/main/scala/chisel3/iotesters/SteppedHWIOTester.scala:172: type mismatch;
    [error]  found   : chisel3.core.Record
    [error]  required: chisel3.Bundle
    [error]     (which expands to)  chisel3.core.Bundle
    [error]     io_info = new IOAccessor(device_under_test.io)

### PR DESCRIPTION
**Pull request by grebe**
Record is a new thing, and FixedPoint got moved to the experimental package.

Closes #88

### CODE REVIEW

**Comment by grebe** [comment]
Oops, I didn't see that Jim fixed this... and I missed something anyways. I removed that part so hopefully #90 and this can be merged simultaneously

**Comment by grebe** [comment]
Oh gosh. I missed #89 too... :(

**Comment by shunshou** [comment]
Means this can be closed, right? as long as #89 and #90 get merged?

@chick can you merge #89 #90 and my #86 ASAP?
